before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm
      - arm64

    ldflags:
      - -X 'main.version={{.Version}}'

archives:
  - replacements:
      darwin: macOS

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - '^refactor:'

release:
  name_template: "{{.ProjectName}}-v{{.Version}}"
