name: build

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'docs/**'
      - 'mkdocs.yaml'
  pull_request:
    paths-ignore:
      - 'docs/**'
      - 'mkdocs.yaml'
 
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.19.0'

      - name: test
        run: |
          go test ./...
